name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'Infrastructure/**' # Only runs if Terraform files change

# These permissions are required for Workload Identity Federation
permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Infrastructure # Tell the runner where the code is

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        # In a real enterprise setup, you might want a manual approval step here!
        run: terraform apply -auto-approve tfplan
